/** @format */

import { CSSProperties } from 'react';

export const layoutStyles: Record<string, CSSProperties> = {
	container: {
		display: 'flex',
		height: '100%',
		width: '100%',
		overflow: 'hidden',
	},
	main: {
		flex: 1,
		display: 'flex',
		flexDirection: 'column',
		overflow: 'hidden',
		background: 'var(--bg-page)',
	},
	topbar: {
		background: 'rgba(255,255,255,0.82)',
		backdropFilter: 'blur(14px)',
		WebkitBackdropFilter: 'blur(14px)',
		borderBottom: '1px solid var(--border)',
		padding: '0 26px',
		height: 60,
		display: 'flex',
		alignItems: 'center',
		gap: 16,
		flexShrink: 0,
		boxShadow: 'var(--shadow-sm)',
	},
	content: {
		flex: 1,
		overflowY: 'auto',
		padding: '22px 26px',
		display: 'flex',
		flexDirection: 'column',
		gap: 18,
	},
	topbarTitle: {
		fontSize: 17,
		fontWeight: 800,
		letterSpacing: '-0.025em',
		display: 'flex',
		alignItems: 'center',
		gap: 8,
	},
	topbarSub: {
		fontSize: 11,
		color: 'var(--text-muted)',
		fontFamily: 'var(--font-mono)',
		letterSpacing: '0.06em',
		marginTop: 1,
	},
	liveDot: {
		width: 8,
		height: 8,
		borderRadius: '50%',
		background: 'var(--success)',
		display: 'inline-block',
		animation: 'liveBlink 2s infinite',
	},
	searchContainer: {
		display: 'flex',
		alignItems: 'center',
		gap: 8,
		background: 'var(--bg-surface)',
		border: '1px solid var(--border-strong)',
		borderRadius: 'var(--r-md)',
		padding: '0 14px',
		height: 36,
		width: 230,
		fontSize: 13,
		color: 'var(--text-muted)',
		cursor: 'text',
		boxShadow: 'var(--shadow-sm)',
	},
	kbd: {
		fontSize: 10,
		fontFamily: 'var(--font-mono)',
		background: 'var(--bg-raised)',
		border: '1px solid var(--border)',
		color: 'var(--text-faint)',
		padding: '1px 6px',
		borderRadius: 4,
	},
	buttonSecondary: {
		height: 36,
		borderRadius: 'var(--r-md)',
		border: '1px solid var(--border-strong)',
		background: 'var(--bg-surface)',
		color: 'var(--text-secondary)',
		fontSize: 13,
		fontWeight: 500,
		padding: '0 14px',
		boxShadow: 'var(--shadow-sm)',
		cursor: 'pointer',
	},
	buttonPrimary: {
		height: 36,
		borderRadius: 'var(--r-md)',
		border: 'none',
		background: 'var(--brand)',
		color: '#fff',
		fontSize: 13,
		fontWeight: 600,
		padding: '0 18px',
		boxShadow: '0 2px 8px rgba(26,86,219,0.28)',
		cursor: 'pointer',
	},
	buttonMini: {
		height: 30,
		borderRadius: 'var(--r-sm)',
		border: '1px solid var(--border-strong)',
		background: 'var(--bg-raised)',
		color: 'var(--text-secondary)',
		fontSize: 12,
		fontWeight: 500,
		padding: '0 12px',
		cursor: 'pointer',
	},
	select: {
		background: 'var(--bg-raised)',
		border: '1px solid var(--border)',
		color: 'var(--text-secondary)',
		borderRadius: 'var(--r-sm)',
		padding: '4px 10px',
		fontSize: 11,
		fontFamily: 'var(--font-mono)',
	},
	kpiGrid: { display: 'grid', gridTemplateColumns: 'repeat(5, 1fr)', gap: 13 },
	analyticsGrid: {
		display: 'grid',
		gridTemplateColumns: '1fr 1fr 320px',
		gap: 14,
	},
	kanbanGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(4, 1fr)',
		gap: 13,
	},
	bottomGrid: {
		display: 'grid',
		gridTemplateColumns: 'repeat(3, 1fr)',
		gap: 14,
	},
};

export const sidebarStyles: Record<string, CSSProperties> = {
	aside: {
		width: 228,
		minWidth: 228,
		background: 'var(--bg-surface)',
		borderRight: '1px solid var(--border)',
		display: 'flex',
		flexDirection: 'column',
		overflow: 'hidden',
	},
	logoContainer: {
		padding: '20px 18px 16px',
		borderBottom: '1px solid var(--border)',
		display: 'flex',
		alignItems: 'center',
		gap: 11,
	},
	logoIcon: {
		width: 34,
		height: 34,
		borderRadius: 'var(--r-md)',
		flexShrink: 0,
		background: 'linear-gradient(135deg, #1a56db, #7c3aed)',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		boxShadow: '0 2px 8px rgba(26,86,219,0.3)',
	},
	logoText: {
		fontSize: 15,
		fontWeight: 800,
		letterSpacing: '-0.02em',
		lineHeight: 1.2,
	},
	logoSubtext: {
		fontSize: 10,
		color: 'var(--text-muted)',
		fontFamily: 'var(--font-mono)',
		letterSpacing: '0.07em',
		lineHeight: 1.3,
	},
	nav: { flex: 1, padding: '10px 10px', overflowY: 'auto' },
	sectionHeader: {
		fontSize: 9,
		fontWeight: 600,
		letterSpacing: '0.12em',
		textTransform: 'uppercase',
		color: 'var(--text-faint)',
		padding: '12px 10px 5px',
		fontFamily: 'var(--font-mono)',
	},
	navButton: {
		width: '100%',
		display: 'flex',
		alignItems: 'center',
		gap: 9,
		padding: '8px 10px',
		borderRadius: 'var(--r-md)',
		marginBottom: 1,
		textAlign: 'left',
		cursor: 'pointer',
		transition: 'all 0.15s',
		position: 'relative',
	},
	activeIndicator: {
		position: 'absolute',
		left: -10,
		top: '50%',
		transform: 'translateY(-50%)',
		width: 3,
		height: 18,
		background: 'var(--brand)',
		borderRadius: '0 3px 3px 0',
	},
	badge: {
		fontSize: 10,
		fontFamily: 'var(--font-mono)',
		padding: '1px 7px',
		borderRadius: 999,
		fontWeight: 500,
	},
	profileContainer: {
		display: 'flex',
		alignItems: 'center',
		gap: 10,
		padding: '9px 12px',
		borderRadius: 'var(--r-md)',
		background: 'var(--bg-raised)',
		border: '1px solid var(--border)',
		cursor: 'pointer',
	},
	profileAvatar: {
		width: 30,
		height: 30,
		borderRadius: 8,
		background: 'linear-gradient(135deg,#1a56db,#7c3aed)',
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: 11,
		fontWeight: 700,
		color: '#fff',
		flexShrink: 0,
		fontFamily: 'var(--font-mono)',
	},
	profileSubtext: {
		fontSize: 10,
		color: 'var(--text-muted)',
		fontFamily: 'var(--font-mono)',
	},
};

export const kpiStyles: Record<string, CSSProperties> = {
	card: {
		background: 'var(--bg-surface)',
		border: '1px solid var(--border)',
		borderRadius: 'var(--r-lg)',
		padding: '15px 17px',
		boxShadow: 'var(--shadow-sm)',
		position: 'relative',
		overflow: 'hidden',
		cursor: 'default',
		transition: 'box-shadow 0.2s, transform 0.2s',
	},
	accent: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		height: 3,
		borderRadius: 'var(--r-lg) var(--r-lg) 0 0',
	},
	icon: {
		position: 'absolute',
		top: 13,
		right: 14,
		width: 30,
		height: 30,
		borderRadius: 8,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: 14,
	},
	label: {
		fontSize: 10,
		fontWeight: 600,
		letterSpacing: '0.06em',
		textTransform: 'uppercase',
		color: 'var(--text-muted)',
		fontFamily: 'var(--font-mono)',
		marginBottom: 7,
	},
	value: {
		fontSize: 26,
		fontWeight: 800,
		letterSpacing: '-0.03em',
		color: 'var(--text-primary)',
		lineHeight: 1,
	},
	delta: {
		marginTop: 6,
		fontSize: 11,
		fontFamily: 'var(--font-mono)',
		display: 'flex',
		alignItems: 'center',
		gap: 3,
	},
};

export const metricStyles: Record<string, CSSProperties> = {
	row: {
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'space-between',
		padding: '9px 0',
		borderBottom: '1px solid var(--border)',
	},
	rowLabel: {
		display: 'flex',
		alignItems: 'center',
		gap: 8,
		fontSize: 13,
		color: 'var(--text-secondary)',
		fontWeight: 500,
	},
	iconWrapper: {
		width: 26,
		height: 26,
		borderRadius: 7,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: 13,
		flexShrink: 0,
	},
	rowValue: { fontFamily: 'var(--font-mono)', fontSize: 14, fontWeight: 600 },
	avatar: {
		width: 30,
		height: 30,
		borderRadius: 8,
		display: 'flex',
		alignItems: 'center',
		justifyContent: 'center',
		fontSize: 10,
		fontWeight: 700,
		color: '#fff',
		flexShrink: 0,
		fontFamily: 'var(--font-mono)',
	},
	rowSubtext: {
		fontSize: 10,
		color: 'var(--text-muted)',
		fontFamily: 'var(--font-mono)',
	},
	progressBg: {
		width: 56,
		height: 4,
		background: 'var(--bg-sunken)',
		borderRadius: 2,
		overflow: 'hidden',
	},
	progressFill: {
		height: '100%',
		background: 'var(--success)',
		borderRadius: 2,
	},
	activityText: {
		fontSize: 12,
		fontWeight: 500,
		color: 'var(--text-primary)',
		lineHeight: 1.4,
	},
};
